userinp = input('Digite alguma coisa para sabre suas propriedades: ')
print('O tipo primitivo desse valor é: ', type(userinp))
print('Só tem espaços?', userinp.isspace())
print('É um número?', userinp.isnumeric())
print('É alfabético?', userinp.isalpha())
print('É alfanumérico?', userinp.isalnum())
print('Está em maiúsculas?', userinp.isupper())
print('Está em minúsculas?', userinp.islower())
print('Está capitalizada?', userinp.istitle())
